[tools]
"github:lune-org/lune" = "0.10.4"
"github:evaera/moonwave" = "1.3.0"
deno = "2.5.6"

[tasks.check]
description = "Run checks for formatting and linting (ensures locked and all features)"
shell = "bash -c"
run = [
    "deno biome format --check",
    "deno task lint"
]

[tasks.build]
description = "Generate and build documentation site"
shell = "bash -c"
run = "pnpm build"

[tasks.deploy]
description = "Deploy site"
shell = "bash -c"
run = "pnpm deploy"

[settings]
experimental = true
lockfile = true

